language: node_js
node_js:
    - '12.13.0'
before_deploy:
    - 'CI=false npm run build'
deploy:
    provider: script
    skip_cleanup: true
    script: sh scripts/deploy.sh
    on:
        branch: master
